### ISSUE TITLE
Lazy loading the translation based on modules

### ISSUE THREAD

**Issue by hpardess** [nsia-infosys/eBreshna-web#44]

**Comment by MirwaisAkrami** [comment]
Looking to the scale of the project, it will soon be a mess if we keep all of our translations in one file and it will become a maintenance headache.
That is why we need to have a modular approach, i.e splitting the translation files based on the modules.
Each module will have the translation files for all the languages, specific to itself. and in the run time, when a module is loaded we will load its related translation file as well.
It is much easier to send, translate and maintain smaller files and we will also be able to avoid repetition errors and all.
And also we can keep all those things that are common in one place and reuse it in any module we need.

**Comment by MirwaisAkrami** [comment]
Explanation of the [f964861 ](https://github.com/nsia-infosys/eBreshna-web/commit/f9648619fbf134bc52087c2cc79694ae19303761) commit, implementing lazy loaded ngx-translation in a  multi level lazy loaded modules project.

Here is how it is carried out

- We create the translation files for each module under a directory with the name of each module
```
|── module-name
|      |── en.ts
|      |── ps.ts
|      |── fa.ts
|── en.ts (Main file)
|── ps.ts (Main file)
|── fa.ts (Main file)
```

- The structure of the file must be like below for the all the files (except the main translation files)

```
export const module = {
   key: 'value'
}
```
Note: the module here is just variable, don't mix it with angular's module

- The main translation files should have a key with the name `M` ( Convention )
```
. . .
// other contents
. . .
M: {}
```
- We create a guard that implements `canActivate` which will run before the modules loaded in the app-routing 

- We assign the `moduleName` (a convention ) in the data of that route to the name of that module and access it in the translate guard.
```
path: 'payments',
canActivate: [TranslateGuard],
data: { moduleName: 'payments' },
```
Note: The `moduleName` must be the same as the folder name containing the translation files for that module.

- Translate guard also expect the names of the files to be the same as the language extensions.
- After finding the desired translation, for a specific language, we assign the `M` in the main translation file, to the module specific translation object

```
// Setting for english language
const moduleEn = this.loadModuleSpecificTranslations(route.data.moduleName, 'en');
if(moduleEn) {
   enLang.data.M = moduleEn;
}
```

- And in the HTML file, access the translations like this.

```
<label>{{'M.TRANSLATE_KEY' | translate }}</label>
```

#### Important points
- Since we have three and even four level lazy loading in some modules, then ngx-translate `isolate: true` is not applicable to our scenario.
- Since only the `M` object of the main files is changed, we can access all the other keys of the main files, which is good for using common translations between modules.
- Plus point as I said before is the clear and maintainable nature of translation files.
- We may object this approach because of using those many files, but if we think, that big chunk of using only one file is approximately equal to using many smaller sized files.


You can check the full implementation in this [commit](https://github.com/nsia-infosys/eBreshna-web/commit/f9648619fbf134bc52087c2cc79694ae19303761) just before the comment
